services:
  watchable:
    build: .
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /dev/bus/usb:/dev/bus/usb
    environment:
      TUNER_URL: ${TUNER_URL}
      CRON_MINUTES: ${CRON_MINUTES:-10,40}
      TZ: Asia/Tokyo
      PYTHONUNBUFFERED: 1
